import Fluent
import Vapor

struct TriviaSeeder {
    static func seed(on db: Database) async throws {
        let existing = try await Question.query(on: db).count()
        guard existing == 0 else { return }

        let questions: [Question] = [
            .init(text: "What is my favorite anime",
                  options: ["Clannad", "Fate/stay", "The Quintessential Quintuplets", "High school dxd"],
                  correctAnswer: "Clannad",
                  type: .multipleChoice),
            .init(text: "What is the name of my Highschool",
                  options: ["Bronx high school of science", "Bronx Academy for software engineer"],
                  correctAnswer: "Bronx Academy for software engineer",
                  type: .multipleChoice),
            .init(text: "What are the names of my brothers",
                  options: [],
                  correctAnswer: "Devin and Felix",
                  type: .text),
            .init(text: "What is my favorite Vocaloid song",
                  options: ["White snow princess", "Secret Police", "The madness of duke venomania", "Six Trillion Years and Overnight Story"],
                  correctAnswer: "White snow princess",
                  type: .multipleChoice),
            .init(text: "What is my favorite Ado song",
                  options: ["Odo", "Sakura Biyori", "Crime and Punishment", "Divinity"],
                  correctAnswer: "Crime and Punishment",
                  type: .multipleChoice),
            .init(text: "Who is my favorite character in Danganronpa",
                  options: ["K1-Bo", "Kiyotaka Ishimaru", "Juzo Sakakura", "Ibuki Mioda"],
                  correctAnswer: "Ibuki Mioda",
                  type: .multipleChoice),
            .init(text: "What team was I captain of during Albany esports",
                  options: ["Overwatch", "Valorant", "League", "SF6"],
                  correctAnswer: "Valorant",
                  type: .multipleChoice),
            .init(text: "When I skipped my prom where did I go instead",
                  options: ["Bahamas", "Mexico", "Puerto Rico", "Florida"],
                  correctAnswer: "Mexico",
                  type: .multipleChoice),
            .init(text: "Favorite Japanese food",
                  options: ["Ramen", "Kiritanpo", "Yakitori", "Soba"],
                  correctAnswer: "Kiritanpo",
                  type: .multipleChoice),
            .init(text: "Who’s my favorite American artist / band",
                  options: ["Bruno Mars", "Metallica", "Lada Gaga", "My Chemical Romance"],
                  correctAnswer: "Bruno Mars",
                  type: .multipleChoice),
            .init(text: "What is my favorite Jojo Part",
                  options: ["Steel ball run", "Stardust Crusaders", "Golden Wind", "Phantom Blood"],
                  correctAnswer: "Steel ball run",
                  type: .multipleChoice),
            .init(text: "Who is my favorite Pokemon",
                  options: ["Charmander", "GimmiGhoul", "Skitty", "Palkia"],
                  correctAnswer: "Charmander",
                  type: .multipleChoice),
            .init(text: "Who is my favorite Love live character",
                  options: ["Ruby Kurosawa", "Kotori Minami", "Rina Tennoji", "Nozomi Tojo"],
                  correctAnswer: "Kotori Minami",
                  type: .multipleChoice),
            .init(text: "What is my most played game on Steam",
                  options: ["Warframe", "Final Fantasy 14", "Destiny 2", "Elding Ring"],
                  correctAnswer: "Final Fantasy 14",
                  type: .multipleChoice),
            .init(text: "What is my favorite monster in Monster Hunter series",
                  options: ["Mizutsune", "Lunastra", "Crimson glow valstrax", "Thunder Serpent Narwa"],
                  correctAnswer: "Mizutsune",
                  type: .multipleChoice),
            .init(text: "What is the name of my anime club advisor in high school",
                  options: ["Vanessa", "Nicole"],
                  correctAnswer: "Vanessa",
                  type: .multipleChoice),
            .init(text: "What game did I go pro in during high school",
                  options: [],
                  correctAnswer: "overwatch",
                  type: .text),
            .init(text: "What school did I attend for study abroad",
                  options: ["Akita Internation University", "Tokyo U", "Waseda University", "Kyoto University"],
                  correctAnswer: "Akita Internation University",
                  type: .multipleChoice),
            .init(text: "Who did I meet in the Nintendo store during the year of 2018",
                  options: [],
                  correctAnswer: "Jeff Kaplan",
                  type: .text,
                  hint: "What game was I playing in high school"),
            .init(text: "Who do I love the most?",
                  options: ["Friends", "Friends", "Friends", "Friends"],
                  correctAnswer: "Friends",
                  type: .multipleChoice)
        ]

        try await questions.create(on: db)
    }
}
